package main

import "html/template"

var modernPageWithProgress = template.Must(template.New("modern-progress").Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{.Title}} · Web File Manager</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1080px;margin:0 auto;padding:28px 20px}.nav{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:30px}.brand{font-size:20px;font-weight:750;color:#172033;text-decoration:none}.nav-right{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.nav a{color:#475467;text-decoration:none}.nav a:hover{color:#175cd3}.role{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eaf2ff;color:#175cd3;font-size:12px;font-weight:700}.button,button{border:0;border-radius:8px;background:#175cd3;color:#fff;padding:10px 14px;font:inherit;font-size:14px;cursor:pointer;text-decoration:none;display:inline-block}.button.secondary{background:#eef2f7;color:#344054}.button.danger{background:#b42318}.hero{margin-bottom:22px}.eyebrow{color:#667085;font-size:14px;margin:0 0 6px}.hero h1{font-size:32px;letter-spacing:-.03em;margin:0}.card{background:#fff;border:1px solid #e4eaf2;border-radius:16px;padding:24px;box-shadow:0 10px 24px rgba(16,24,40,.04);margin-bottom:20px}.card h2{font-size:18px;margin:0 0 8px}.muted{color:#667085;font-size:14px}.upload input{max-width:520px;width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;margin:10px 0 14px}.progress-area{margin-top:16px}.progress-head{display:flex;justify-content:space-between;gap:12px;color:#667085;font-size:13px;margin-bottom:7px}.progress-track{height:8px;border-radius:999px;background:#e7ecf3;overflow:hidden}.progress-bar{height:100%;width:0;background:#175cd3;border-radius:999px;transition:width .15s ease}.status{margin:9px 0 0;font-size:13px;color:#667085}table{width:100%;border-collapse:collapse}td,th{padding:14px 8px;border-bottom:1px solid #edf0f5;text-align:left;font-size:14px}th{color:#667085;font-weight:600}.actions{white-space:nowrap}.empty{text-align:center;padding:28px 10px}.auth{max-width:440px;margin:9vh auto}.auth h1{margin:20px 0 8px;font-size:28px}.field{margin:18px 0}.field label{display:block;font-size:14px;font-weight:650;margin-bottom:7px}.field input{width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.error{padding:11px 13px;border-radius:8px;background:#fff1f0;color:#b42318;margin:16px 0;font-size:14px}.auth-footer{margin-top:18px;font-size:14px;color:#667085}.auth-footer a{color:#175cd3}@media(max-width:680px){.shell{padding:20px 14px}.nav{align-items:flex-start;flex-direction:column}.hero h1{font-size:27px}.hide-mobile{display:none}.card{padding:18px}.actions .button{padding:8px 10px}}
</style></head><body><main class="shell">{{if .User}}<nav class="nav"><a class="brand" href="/">Web File Manager</a><div class="nav-right"><span class="muted">{{.User}}</span><span class="role">{{if .IsAdmin}}Administrator{{else}}User{{end}}</span><a href="/change-password">Change password</a>{{if .IsAdmin}}<a class="button secondary" href="/admin">Admin</a>{{end}}<form method="post" action="/logout"><button class="button secondary" type="submit">Sign out</button></form></div></nav><div class="hero"><p class="eyebrow">Secure personal storage</p><h1>My files</h1></div><section class="card upload"><h2>Upload a file</h2><p class="muted">Files are encrypted before they are written to disk. Maximum size: 100 MB.</p><form id="upload-form" method="post" action="/upload" enctype="multipart/form-data"><input id="file-input" type="file" name="file" required><br><button id="upload-button" type="submit">Encrypt and upload</button><div id="upload-progress" class="progress-area" hidden><div class="progress-head"><span id="upload-status">Preparing upload…</span><span id="upload-percent">0%</span></div><div class="progress-track"><div id="upload-bar" class="progress-bar"></div></div></div></form></section><section class="card"><h2>Your files</h2>{{if .Files}}<table><tr><th>Filename</th><th class="hide-mobile">Size</th><th class="hide-mobile">Uploaded</th><th>Actions</th></tr>{{range .Files}}<tr><td>{{.OriginalName}}</td><td class="hide-mobile">{{.Size}} bytes</td><td class="hide-mobile">{{.UploadedAt.Format "2006-01-02 15:04"}}</td><td class="actions"><a class="button download-link" data-filename="{{.OriginalName}}" href="/download?id={{.ID}}">Download</a> <form style="display:inline" method="post" action="/delete?id={{.ID}}"><button class="button danger" type="submit">Delete</button></form></td></tr>{{end}}</table>{{else}}<div class="empty"><p class="muted">No files yet.</p></div>{{end}}</section><script>
(() => {
  const form = document.getElementById('upload-form');
  const input = document.getElementById('file-input');
  const button = document.getElementById('upload-button');
  const progress = document.getElementById('upload-progress');
  const bar = document.getElementById('upload-bar');
  const percent = document.getElementById('upload-percent');
  const status = document.getElementById('upload-status');
  form.addEventListener('submit', (event) => {
    event.preventDefault();
    if (!input.files.length) return;
    const xhr = new XMLHttpRequest();
    const formData = new FormData(form);
    button.disabled = true;
    input.disabled = true;
    progress.hidden = false;
    status.textContent = 'Uploading and encrypting…';
    xhr.open('POST', form.action);
    xhr.upload.addEventListener('progress', (event) => {
      if (!event.lengthComputable) { status.textContent = 'Uploading…'; return; }
      const value = Math.round(event.loaded / event.total * 100);
      bar.style.width = value + '%';
      percent.textContent = value + '%';
      status.textContent = value === 100 ? 'Finishing encryption…' : 'Uploading…';
    });
    xhr.addEventListener('load', () => {
      if (xhr.status >= 200 && xhr.status < 400) {
        bar.style.width = '100%'; percent.textContent = '100%'; status.textContent = 'Upload complete';
        window.setTimeout(() => window.location.reload(), 500);
      } else {
        status.textContent = xhr.responseText.trim() || ('Upload failed (' + xhr.status + ')'); button.disabled = false; input.disabled = false;
      }
    });
    xhr.addEventListener('error', () => { status.textContent = 'Network error during upload'; button.disabled = false; input.disabled = false; });
    xhr.send(formData);
  });
  document.querySelectorAll('.download-link').forEach((link) => {
    link.addEventListener('click', async (event) => {
      event.preventDefault();
      const original = link.textContent;
      link.textContent = 'Downloading…'; link.style.pointerEvents = 'none';
      try {
        const response = await fetch(link.href);
        if (!response.ok || !response.body) throw new Error('download failed');
        const total = Number(response.headers.get('Content-Length')) || 0;
        const reader = response.body.getReader(); let loaded = 0; const chunks = [];
        while (true) {
          const part = await reader.read(); if (part.done) break; chunks.push(part.value); loaded += part.value.length;
          link.textContent = total ? 'Downloading ' + Math.round(loaded / total * 100) + '%…' : 'Downloading…';
        }
        const blob = new Blob(chunks); const url = URL.createObjectURL(blob); const anchor = document.createElement('a');
        anchor.href = url; anchor.download = link.dataset.filename || 'download'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
      } catch (error) { window.location.href = link.href; }
      link.textContent = original; link.style.pointerEvents = '';
    });
  });
})();
</script>{{else}}<section class="card auth"><a class="brand" href="/">Web File Manager</a><h1>{{.Heading}}</h1><p class="muted">Private, encrypted file storage.</p>{{if .Error}}<div class="error">{{.Error}}</div>{{end}}{{if eq .Page "login"}}<form method="post" action="/login"><div class="field"><label>Username</label><input name="username" required autofocus></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button type="submit">Sign in</button></form><p class="auth-footer">No account yet? <a href="/register">Create one</a></p>{{else}}<form method="post" action="/register"><div class="field"><label>Username</label><input name="username" pattern="[A-Za-z0-9_-]{3,32}" required autofocus></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><button type="submit">Register</button></form><p class="auth-footer">Already have an account? <a href="/login">Sign in</a></p>{{end}}</section>{{end}}</main></body></html>`))

var modernPasswordPage = template.Must(template.New("modern-password").Parse(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Change password · Web File Manager</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1080px;margin:0 auto;padding:28px 20px}.nav{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:30px}.brand{font-size:20px;font-weight:750;color:#172033;text-decoration:none}.nav-right{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.nav a{color:#475467;text-decoration:none}.button,button{border:0;border-radius:8px;background:#175cd3;color:#fff;padding:10px 14px;font:inherit;font-size:14px;cursor:pointer;text-decoration:none}.button.secondary{background:#eef2f7;color:#344054}.role{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eaf2ff;color:#175cd3;font-size:12px;font-weight:700}.card{max-width:520px;background:#fff;border:1px solid #e4eaf2;border-radius:16px;padding:26px;box-shadow:0 10px 24px rgba(16,24,40,.04)}.card h1{margin:0 0 8px}.muted{color:#667085;font-size:14px}.field{margin:20px 0}.field label{display:block;font-size:14px;font-weight:650;margin-bottom:7px}.field input{width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.error{padding:11px 13px;border-radius:8px;background:#fff1f0;color:#b42318;margin:16px 0;font-size:14px}@media(max-width:680px){.shell{padding:20px 14px}.nav{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="shell"><nav class="nav"><a class="brand" href="/">Web File Manager</a><div class="nav-right"><span class="muted">{{.User}}</span><span class="role">{{if .IsAdmin}}Administrator{{else}}User{{end}}</span><a href="/">My files</a>{{if .IsAdmin}}<a class="button secondary" href="/admin">Admin</a>{{end}}<form method="post" action="/logout"><button class="button secondary" type="submit">Sign out</button></form></div></nav><section class="card"><h1>Change password</h1><p class="muted">Update the password for your account.</p>{{if .Error}}<div class="error">{{.Error}}</div>{{end}}<form method="post" action="/change-password"><div class="field"><label>Current password</label><input type="password" name="current_password" required autofocus></div><div class="field"><label>New password</label><input type="password" name="new_password" minlength="8" required></div><div class="field"><label>Confirm new password</label><input type="password" name="confirm_password" minlength="8" required></div><button type="submit">Change password</button></form></section></main></body></html>`))

var modernAdminPageWithReset = template.Must(template.New("modern-admin-reset").Parse(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin · Web File Manager</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1000px;margin:0 auto;padding:28px 20px}.nav{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:30px}.brand{font-size:20px;font-weight:750;color:#172033;text-decoration:none}.nav-right{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.nav a{color:#475467;text-decoration:none}.button,button{border:0;border-radius:8px;background:#175cd3;color:#fff;padding:9px 12px;font:inherit;font-size:13px;cursor:pointer;text-decoration:none}.button.secondary{background:#eef2f7;color:#344054}.card{background:#fff;border:1px solid #e4eaf2;border-radius:16px;padding:24px;box-shadow:0 10px 24px rgba(16,24,40,.04);margin-bottom:20px}.card h1{margin:0 0 8px}.card h2{font-size:18px;margin:0 0 16px}.muted{color:#667085;font-size:14px}.stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.stat{padding:18px;border:1px solid #e4eaf2;border-radius:12px}.stat strong{display:block;font-size:28px;margin-bottom:4px}table{width:100%;border-collapse:collapse}td,th{padding:14px 8px;border-bottom:1px solid #edf0f5;text-align:left;font-size:14px}th{color:#667085;font-weight:600}.role{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eaf2ff;color:#175cd3;font-size:12px;font-weight:700}.reset-form{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.reset-form input{width:170px;padding:8px;border:1px solid #cbd5e1;border-radius:7px;font:inherit;font-size:13px}.hint{margin-top:0}@media(max-width:680px){.shell{padding:20px 14px}.nav{align-items:flex-start;flex-direction:column}.card{padding:18px}.stats{grid-template-columns:1fr}.reset-form input{width:100%}}
</style></head><body><main class="shell"><nav class="nav"><a class="brand" href="/">Web File Manager</a><div class="nav-right"><a href="/">My files</a><a href="/change-password">Change password</a><form method="post" action="/logout"><button class="button secondary" type="submit">Sign out</button></form></div></nav><section class="card"><p class="muted">Administrator area</p><h1>User management</h1><p class="muted hint">Manage accounts and reset passwords. File contents remain a private user function.</p></section><section class="card"><h2>Overview</h2><div class="stats"><div class="stat"><strong>{{.UserCount}}</strong><span class="muted">Registered users</span></div><div class="stat"><strong>{{.AdminCount}}</strong><span class="muted">Administrators</span></div></div></section><section class="card"><h2>Users</h2><table><tr><th>Username</th><th>Role</th><th>Reset password</th></tr>{{range .Users}}<tr><td>{{.Username}}</td><td>{{if .IsAdmin}}<span class="role">Administrator</span>{{else}}User{{end}}</td><td><form class="reset-form" method="post" action="/admin/reset-password"><input type="hidden" name="username" value="{{.Username}}"><input type="password" name="new_password" minlength="8" placeholder="New password" required><button type="submit">Reset</button></form></td></tr>{{end}}</table></section></main></body></html>`))
